# Generated by Django 5.0.6 on 2024-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(null=True, verbose_name='Телефон'),
        ),
    ]
