# Generated by Django 5.0.6 on 2024-06-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('student', models.ForeignKey(limit_choices_to={'role__title': 'Ученик'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_timetable', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role__title': 'Учитель'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
