# Generated by Django 5.0.6 on 2024-06-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Темы')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Темы постов',
                'verbose_name_plural': 'Темы постов',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/posts/%Y/%m/', verbose_name='Изображение')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('themes', models.ManyToManyField(blank=True, related_name='themes', to='mainblog.themepost', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Посты',
                'verbose_name_plural': 'Посты',
                'ordering': ['-time_create'],
            },
        ),
    ]
